name: Build and deploy ASP.Net Core app to Azure Web App - gitCodeWebCode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build the project
      - name: Build project
        run: dotnet build MyApi.csproj --configuration Release

      # Publish project to a relative path
      
      - name: Publish project
        run: |
          $publishDir = "$PWD\publish\myapp"
          mkdir $publishDir
          dotnet publish MyApi.csproj --configuration Release --output $publishDir
          echo "Published to $publishDir"


      # Upload published files as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish\myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E5B6DE1F0CB449A930BA1DB4ACCBB9F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_12611FAE0C004686AC3899A91E69430C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C95A165729F4E299D027031220DE959 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gitCodeWebCode'
          slot-name: 'Production'
          package: publish\myapp
